FROM		debian:buster

RUN			apt update && apt upgrade -y
RUN			apt install -y nginx
RUN			apt install -y tor
RUN			apt install -y openssh-server

RUN			mkdir 			-p /etc/nginx/sites-available
COPY		./nginx.conf	/etc/nginx/sites-available/nginx.conf

RUN			mkdir -p 		/var/www/html
COPY		./index.html	/var/www/html/index.html

RUN			mkdir -p 		/var/run/sshd
COPY		./sshd_config	/etc/ssh/sshd_config

RUN			echo "root:123soleil" | chpasswd

COPY		./init.sh		/init.sh

			# Path to hostname cat /var/lib/tor/my-website/hostname
COPY		./torrc			/etc/tor/torrc 

CMD			["sh", "init.sh"]
